#!/bin/sh

ERTS_BIN_DIR=$(cd ${0%/*} && pwd)

export ROOTDIR=${ERTS_BIN_DIR%/*}

START_ERL=`cat $ROOTDIR/releases/start_erl.data`
ERTS_VSN=${START_ERL% *}
APP_VSN=${START_ERL#* }

export BINDIR=$ROOTDIR/erts-$ERTS_VSN/bin
export EMU=beam
export PROGNAME=`echo $0 | sed 's/.*\///'`

exec $BINDIR/erlexec -noshell -boot $ROOTDIR/releases/$APP_VSN/osc \
    -args_file $ROOTDIR/etc/vm.args -config $ROOTDIR/etc/app.config
